# https://taskfile.dev

version: '3'

tasks:
  init-cmake:
    cmds:
      - mkdir build
      - cd build && cmake ..
  build:
    dir: "./build"
    cmds:
      - make
  run:
    dir: "./build"
    cmds:
      - task: build
      - ./sealeo
  lint:
    cmds:
      - clang-format --dry-run --Werror --style=file $(find src/ -name '*.cc' -o -name '*.h')
  format:
    cmds:
      - clang-format -i --style=file $(find src/ -name '*.cc' -o -name '*.h')
